# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webbapp64hylaw6bfrd2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://containterregistry64hylaw6bfrd2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9ee72f897cd74d5fa8bcab3527c1386e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d9c4a166ff4a470cbbf36f9bd774e9d1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: containterregistry64hylaw6bfrd2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9ee72f897cd74d5fa8bcab3527c1386e }}/compressor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webbapp64hylaw6bfrd2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_510b87348f754505a4941af481b77565 }}
        images: 'containterregistry64hylaw6bfrd2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9ee72f897cd74d5fa8bcab3527c1386e }}/compressor:${{ github.sha }}'