# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webbapp7cwkv6diblxjy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to ACR
      uses: docker/login-action@v2
      with:
        registry: containterregistry7cwkv6diblxjy.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: containterregistry7cwkv6diblxjy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed46d63d1ef4455981d1da2ee37b5f67 }}/containterregistry7cwkv6diblxjy.azurecr.io/compressor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webbapp7cwkv6diblxjy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3d2a42cc8fcf4a50a9073e26ebdae304 }}
        images: 'containterregistry7cwkv6diblxjy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed46d63d1ef4455981d1da2ee37b5f67 }}/containterregistry7cwkv6diblxjy.azurecr.io/compressor:${{ github.sha }}'
